# Name - Nikhil Singh Kushwah
# ID - 1001510381

In [205]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import openpyxl as px
import graphviz
import pydotplus
from sklearn.externals.six import StringIO  
from IPython.display import Image
from sklearn.tree import export_graphviz
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Task 1: 

In [206]:
df = pd.read_excel('DATASET.xlsx', header=0)
df.head()
df.describe()
Class = []
for index, row in df.iterrows():
    temp = 1
    for x in df.columns:
        if row[x]=='CL3' or row[x]=='CL4' or row[x]=='CL5' or row[x]=='CL6':
            temp=0
    if temp == 0:
        Class.append('USER')
    else:
        Class.append('NOUSER')
        
df_class = pd.DataFrame({'Class': Class})
print(df_class)
df.join(df_class)
df_updated= pd.concat([df, df_class], axis=1)
df_updated.head()

       Class
0     NOUSER
1       USER
2     NOUSER
3       USER
4     NOUSER
5     NOUSER
6     NOUSER
7     NOUSER
8     NOUSER
9     NOUSER
10    NOUSER
11      USER
12      USER
13    NOUSER
14    NOUSER
15    NOUSER
16    NOUSER
17    NOUSER
18    NOUSER
19      USER
20    NOUSER
21    NOUSER
22    NOUSER
23      USER
24    NOUSER
25      USER
26    NOUSER
27      USER
28    NOUSER
29    NOUSER
...      ...
1855    USER
1856    USER
1857    USER
1858    USER
1859    USER
1860    USER
1861    USER
1862    USER
1863    USER
1864    USER
1865    USER
1866    USER
1867    USER
1868    USER
1869    USER
1870    USER
1871    USER
1872    USER
1873    USER
1874    USER
1875    USER
1876    USER
1877    USER
1878  NOUSER
1879    USER
1880    USER
1881    USER
1882    USER
1883    USER
1884    USER

[1885 rows x 1 columns]


ID      Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0   1  0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545   
1   2 -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886   
2   3  0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523   
3   4 -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615   
4   5  0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340   

    Oscore   Ascore   ...    Ecstasy  Heroin  Ketamine Legalh  LSD Meth  \
0 -0.58331 -0.91699   ...        CL0     CL0       CL0    CL0  CL0  CL0   
1  1.43533  0.76096   ...        CL4     CL0       CL2    CL0  CL2  CL3   
2 -0.84732 -1.62090   ...        CL0     CL0       CL0    CL0  CL0  CL0   
3 -0.01928  0.59042   ...        CL0     CL0       CL2    CL0  CL0  CL0   
4 -0.45174 -0.30172   ...        CL1     CL0       CL0    CL1  CL0  CL0   

  Mushrooms Semer  VSA   Class  
0       CL0   CL0  CL0  NOUSER  
1       CL0   CL0  CL0    USER  
2       CL1   CL0  CL0  NOUSER  
3       CL0   CL0  CL0    USER  
4       CL2   CL0  CL0  NOUSER  

[5 rows x 28 columns]

# Task 2: 

In [208]:
traits = data_new.loc[:,['Age', "Gender", "Education", "Country", "Ethnicity","Nscore", 
        "Escore", "Oscore", "Ascore", "Cscore", "Impulsive","SS"]]
traits.head()
X = traits.as_matrix()
Y = df_updated.loc[:,['Class']]
y = Y.as_matrix()
y

array([['NOUSER'],
       ['USER'],
       ['NOUSER'],
       ...,
       ['USER'],
       ['USER'],
       ['USER']], dtype=object)

In [209]:
X

array([[ 0.49788,  0.48246, -0.05921, ..., -0.00665, -0.21712, -1.18084],
       [-0.07854, -0.48246,  1.98437, ..., -0.14277, -0.71126, -0.21575],
       [ 0.49788, -0.48246, -0.05921, ..., -1.0145 , -1.37983,  0.40148],
       ...,
       [-0.07854,  0.48246,  0.45468, ..., -1.38502,  0.52975, -0.52593],
       [-0.95197,  0.48246, -0.61113, ..., -2.57309,  1.29221,  1.2247 ],
       [-0.95197, -0.48246, -0.61113, ...,  0.41594,  0.88113,  1.2247 ]])

In [210]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)
Decision_tree_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 100,
 max_depth=3, min_samples_leaf=5)
Decision_tree_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [211]:
dot_data = StringIO()
export_graphviz(clf_entropy, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

# TASK 3

In [172]:
bayes_gaussian = GaussianNB()
bayes_gaussian.fit(X_train,y_train)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [201]:
predicted = bayes_gaussian.predict(X_test)
accuracy = accuracy_score(y_test, predicted)
print(predicted)
print('Accuracy score:' + str(accuracy))


['USER' 'USER' 'USER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER'
 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER'
 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER'
 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'USER'
 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'NOUSER' 'USER'
 'USER' 'USER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER'
 'USER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER'
 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'NOUSER'
 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER'
 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER'
 'USER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'USER'
 

# Task 4: 

In [177]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,precision_score
df_prediction = Decision_tree_entropy.predict(X_test)
df_accuracy = accuracy_score(y_test,df_prediction)
df_report = classification_report(y_test,df_prediction)
df_confusion_matrix = confusion_matrix(y_test,df_prediction)
df_precision = precision_score(y_test,df_prediction,average='weighted')

print("Precision_Score:" + str(df_precision*100),'%')
print("Accuracy Score:" + str(df_accuracy*100),'%')
print("Confusion Matrix:")
print(df_confusion_matrix)
print("Report:")
print(report)

Precision_Score:77.43885895775469 %
Accuracy Score:75.79505300353357 %
Confusion Matrix:
[[202  41]
 [ 96 227]]
Report:
             precision    recall  f1-score   support

     NOUSER       0.73      0.81      0.77       250
       USER       0.83      0.76      0.79       316

avg / total       0.79      0.78      0.78       566



In [182]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,precision_score
df_prediction = knn_classifier.predict(X_test)
df_accuracy = accuracy_score(y_test,df_prediction)
df_report = classification_report(y_test,df_prediction)
df_confusion_matrix = confusion_matrix(y_test,df_prediction)
df_precision = precision_score(y_test,df_prediction,average='weighted')

print("Precision_Score:" + str(df_precision*100),'%')
print("Accuracy Score:" + str(df_accuracy*100),'%')
print("Confusion Matrix:")
print(df_confusion_matrix)
print("Report:")
print(report)

Precision_Score:76.7121735367035 %
Accuracy Score:76.5017667844523 %
Confusion Matrix:
[[183  60]
 [ 73 250]]
Report:
             precision    recall  f1-score   support

     NOUSER       0.73      0.81      0.77       250
       USER       0.83      0.76      0.79       316

avg / total       0.79      0.78      0.78       566



In [183]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,precision_score
df_prediction = bayes_gaussian.predict(X_test)
df_accuracy = accuracy_score(y_test,df_prediction)
df_report = classification_report(y_test,df_prediction)
df_confusion_matrix = confusion_matrix(y_test,df_prediction)
df_precision = precision_score(y_test,df_prediction,average='weighted')

print("Precision_Score:" + str(df_precision*100),'%')
print("Accuracy Score:" + str(df_accuracy*100),'%')
print("Confusion Matrix:")
print(df_confusion_matrix)
print("Report:")
print(report)

Precision_Score:80.622814197882 %
Accuracy Score:80.3886925795053 %
Confusion Matrix:
[[195  48]
 [ 63 260]]
Report:
             precision    recall  f1-score   support

     NOUSER       0.73      0.81      0.77       250
       USER       0.83      0.76      0.79       316

avg / total       0.79      0.78      0.78       566



# Task 5: 

In [202]:
knn_classifier = KNeighborsClassifier(n_neighbors=3,metric="euclidean")
knn_classifier.fit(X_train, y_train) 

/home/nikhil/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [203]:
predicted = knn_classifier.predict(X_test)
accuracy = accuracy_score(y_test, predicted)
print(predicted)
print('Accuracy score:' + str(accuracy))

['USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER'
 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'USER'
 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER'
 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'NOUSER'
 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER'
 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER'
 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER'
 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER

# Task 6: 

In [186]:
rf = RandomForestClassifier(n_estimators=15, oob_score=True)
rf.fit(X_train, y_train)

/home/nikhil/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
/usr/local/lib/python3.5/dist-packages/sklearn/ensemble/forest.py:451: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/usr/local/lib/python3.5/dist-packages/sklearn/ensemble/forest.py:456: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=15, n_jobs=1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [187]:
predicted = rf.predict(X_test)
accuracy = accuracy_score(y_test, predicted)

In [204]:
print(predicted)
print('Accuracy score:' + str(accuracy))

['USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER'
 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'USER'
 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'NOUSER' 'USER' 'USER'
 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'NOUSER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER'
 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER'
 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER' 'NOUSER' 'USER' 'NOUSER'
 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER' 'USER' 'NOUSER' 'USER'
 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'NOUSER'
 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER'
 'USER' 'USER' 'NOUSER' 'NOUSER' 'NOUSER' 'NOUSER' 'USER' 'USER' 'USER'
 'USER' 'NOUSER' 'USER' 'USER' 'NOUSER' 'USER' 'USER' 'USER